<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0;net9.0;net10.0</TargetFrameworks>
    <Nullable>annotations</Nullable>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DocumentationFile>$(OutputPath)$(AssemblyName).xml</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition="'$(VersionFromCI)'!=''">
    <Version>$(VersionFromCI)</Version>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
  <PropertyGroup Condition="'$(VersionFromCI)'==''">
    <Version>0.0.0-build</Version>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>
  <PropertyGroup Condition="'$(TF_BUILD)' == 'true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>
  <PropertyGroup>
    <Title>Arcus</Title>
    <PackageId>Arcus</PackageId>
    <Description>Arcus is a C# manipulation library for calculating, parsing, formatting, converting, and comparing both IPv4 and Pv6 addresses and subnets. It accounts for 128-bit numbers on 32-bit platforms.</Description>
    <NeutralLanguage>en</NeutralLanguage>
    <PackageLanguage>en-US</PackageLanguage>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <Company>Sandia National Laboratories</Company>
    <Authors>The Production Tools Team</Authors>
    <Copyright>Copyright 2025 National Technology &amp; Engineering Solutions of Sandia, LLC (NTESS). Under the terms of Contract DE-NA0003525 with NTESS, the U.S. Government retains certain rights in this software</Copyright>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>IP; IP Address; IP Calculator; IPv4; IPv6; ipaddress; ipaddresses; ipv4; ipv4 address; ipv4 calculator; ipv4 network; ipv4 subnetting; ipv4 support; ipv6; ipv6 address; ipv6 calulator; ipv6 network; ipv6 subnetting; ipv6 support; netmask; networking; route prefix; subnet</PackageTags>
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <RepositoryUrl>https://github.com/sandialabs/Arcus.git</RepositoryUrl>
    <PackageProjectUrl>https://github.com/sandialabs/Arcus</PackageProjectUrl>
    <PackageIcon>icon.png</PackageIcon>
    <PackageIconUrl>https://raw.githubusercontent.com/sandialabs/Arcus/main/src/Arcus/icon.png</PackageIconUrl>
    <RepositoryType>git</RepositoryType>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
  <ItemGroup>
    <AdditionalFiles Include="..\..\stylecop.json">
      <Link>stylecop.json</Link>
    </AdditionalFiles>
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
    <None Include="icon.png" Pack="true" Visible="false" PackagePath="" />
    <None Include="icon.txt" Pack="true" Visible="false" PackagePath="" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="AsyncFixer">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Roslynator.Analyzers">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Roslynator.CodeAnalysis.Analyzers">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Roslynator.Formatting.Analyzers">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="SonarAnalyzer.CSharp">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="StyleCop.Analyzers">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
  <!-- If strong-naming is ever adopted, InternalsVisibleTo entries must include PublicKey="..." -->
  <ItemGroup>
    <InternalsVisibleTo Include="Arcus.Tests" />
    <InternalsVisibleTo Include="Arcus.Benchmarks" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <PackageReference Include="Microsoft.Bcl.HashCode" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="BigEndianBitWrapper.Factory.cs">
      <DependentUpon>BigEndianBitWrapper.cs</DependentUpon>
    </Compile>
    <Compile Update="BigEndianBitWrapper.Operators.cs">
      <DependentUpon>BigEndianBitWrapper.cs</DependentUpon>
    </Compile>
    <Compile Update="BigEndianBitWrapper.IComparable.cs">
      <DependentUpon>BigEndianBitWrapper.cs</DependentUpon>
    </Compile>
    <Compile Update="BigEndianBitWrapper.IEquatable.cs">
      <DependentUpon>BigEndianBitWrapper.cs</DependentUpon>
    </Compile>
    <Compile Update="BigEndianBitWrapper.IFormattable.cs">
      <DependentUpon>BigEndianBitWrapper.cs</DependentUpon>
    </Compile>
    <Compile Update="IPAddressRange.ISerializable.cs">
      <DependentUpon>IPAddressRange.cs</DependentUpon>
    </Compile>
    <Compile Update="IPAddressRange.IComparable.cs">
      <DependentUpon>IPAddressRange.cs</DependentUpon>
    </Compile>
    <Compile Update="IPAddressRange.IEquatable.cs">
      <DependentUpon>IPAddressRange.cs</DependentUpon>
    </Compile>
    <Compile Update="IPAddressRange.Operators.cs">
      <DependentUpon>IPAddressRange.cs</DependentUpon>
    </Compile>
    <Compile Update="IPAddressRange.Factory.cs">
      <DependentUpon>IPAddressRange.cs</DependentUpon>
    </Compile>
    <Compile Update="AbstractIPAddressRange.IIPAddressRange.cs">
      <DependentUpon>AbstractIPAddressRange.cs</DependentUpon>
    </Compile>
    <Compile Update="AbstractIPAddressRange.IEnumerable.cs">
      <DependentUpon>AbstractIPAddressRange.cs</DependentUpon>
    </Compile>
    <Compile Update="AbstractIPAddressRange.IFormattable.cs">
      <DependentUpon>AbstractIPAddressRange.cs</DependentUpon>
    </Compile>
    <Compile Update="Subnet.IComparable.cs">
      <DependentUpon>Subnet.cs</DependentUpon>
    </Compile>
    <Compile Update="Subnet.IEquatable.cs">
      <DependentUpon>Subnet.cs</DependentUpon>
    </Compile>
    <Compile Update="Subnet.ISerializable.cs">
      <DependentUpon>Subnet.cs</DependentUpon>
    </Compile>
    <Compile Update="Subnet.Factory.cs">
      <DependentUpon>Subnet.cs</DependentUpon>
    </Compile>
    <Compile Update="Subnet.Operators.cs">
      <DependentUpon>Subnet.cs</DependentUpon>
    </Compile>
  </ItemGroup>
  <Target Name="Husky" BeforeTargets="Restore;CollectPackageReferences" Condition="'$(HUSKY)' != 0">
    <Exec Command="dotnet tool restore" StandardOutputImportance="Low" StandardErrorImportance="High" />
    <Exec
      Command="dotnet husky install"
      StandardOutputImportance="Low"
      StandardErrorImportance="High"
      WorkingDirectory="..\.."
    />
  </Target>
</Project>
